# Generated by scripts/generate.py. Do not edit by hand.
"""One typed async function per contract/manifest.json entry, grouped
by call shape: request-reply returns the response directly,
server-stream/duplex return an async iterator of response chunks.

Asyncio-native, matching the JS SDK. Each function only builds the
wire payload and validates the reply — it takes a `Transport` to
actually speak the wire protocol, which this package does not
implement (see tetherto.qvac_sdk._transport.Transport).
"""

from __future__ import annotations

from collections.abc import AsyncIterable, AsyncIterator

from .._transport import Transport
from . import (
    AudioGenStreamRequest,
    AudioGenStreamResponse,
    BatchCompletionStreamRequest,
    BatchCompletionStreamResponse,
    BciTranscribeRequest,
    BciTranscribeResponse,
    BciTranscribeStreamRequest,
    BciTranscribeStreamResponse,
    CancelRequest,
    CancelResponse,
    ClassifyRequest,
    ClassifyResponse,
    CompletionOrchestrateRequest,
    CompletionOrchestrateResponse,
    CompletionStreamRequest,
    CompletionStreamResponse,
    DeleteCacheRequest,
    DeleteCacheResponse,
    DiffusionStreamRequest,
    DiffusionStreamResponse,
    DownloadAssetRequest,
    DownloadAssetResponse,
    EmbedRequest,
    EmbedResponse,
    FinetuneProgressResponse,
    FinetuneRequest,
    FinetuneResponse,
    GetLoadedModelInfoRequest,
    GetLoadedModelInfoResponse,
    GetModelInfoRequest,
    GetModelInfoResponse,
    GetSystemResourcesRequest,
    GetSystemResourcesResponse,
    HeartbeatRequest,
    HeartbeatResponse,
    LoadModelRequest,
    LoadModelResponse,
    LoggingStreamRequest,
    LoggingStreamResponse,
    ModelProgressResponse,
    ModelRegistryGetModelRequest,
    ModelRegistryGetModelResponse,
    ModelRegistryListRequest,
    ModelRegistryListResponse,
    ModelRegistrySearchRequest,
    ModelRegistrySearchResponse,
    OcrStreamRequest,
    OcrStreamResponse,
    PluginInvokeRequest,
    PluginInvokeResponse,
    PluginInvokeStreamRequest,
    PluginInvokeStreamResponse,
    ProvideRequest,
    ProvideResponse,
    RagProgressResponse,
    RagRequest,
    RagResponse,
    ResumeRequest,
    ResumeResponse,
    StateRequest,
    StateResponse,
    StopProvideRequest,
    StopProvideResponse,
    SuspendRequest,
    SuspendResponse,
    TextToSpeechRequest,
    TextToSpeechResponse,
    TextToSpeechStreamRequest,
    TextToSpeechStreamResponse,
    TranscribeRequest,
    TranscribeResponse,
    TranscribeStreamRequest,
    TranscribeStreamResponse,
    TranslateRequest,
    TranslateResponse,
    UnloadModelRequest,
    UnloadModelResponse,
    UpscaleStreamRequest,
    UpscaleStreamResponse,
    VideoStreamRequest,
    VideoStreamResponse,
)


async def audio_gen_stream(
    transport: Transport, params: AudioGenStreamRequest
) -> AsyncIterator[AudioGenStreamResponse]:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    async for chunk in transport.call_stream(payload):
        yield AudioGenStreamResponse.model_validate(chunk)


async def batch_completion_stream(
    transport: Transport, params: BatchCompletionStreamRequest
) -> AsyncIterator[BatchCompletionStreamResponse]:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    async for chunk in transport.call_stream(payload):
        yield BatchCompletionStreamResponse.model_validate(chunk)


async def bci_transcribe(
    transport: Transport, params: BciTranscribeRequest
) -> AsyncIterator[BciTranscribeResponse]:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    async for chunk in transport.call_stream(payload):
        yield BciTranscribeResponse.model_validate(chunk)


async def bci_transcribe_stream(
    transport: Transport, params: BciTranscribeStreamRequest, up: AsyncIterable[bytes]
) -> AsyncIterator[BciTranscribeStreamResponse]:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    async for chunk in transport.call_duplex(payload, up):
        yield BciTranscribeStreamResponse.model_validate(chunk)


async def cancel(transport: Transport, params: CancelRequest) -> CancelResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return CancelResponse.model_validate(await transport.call(payload))


async def classify(
    transport: Transport, params: ClassifyRequest
) -> AsyncIterator[ClassifyResponse]:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    async for chunk in transport.call_stream(payload):
        yield ClassifyResponse.model_validate(chunk)


async def completion_orchestrate(
    transport: Transport, params: CompletionOrchestrateRequest, up: AsyncIterable[bytes]
) -> AsyncIterator[CompletionOrchestrateResponse]:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    async for chunk in transport.call_duplex(payload, up):
        yield CompletionOrchestrateResponse.model_validate(chunk)


async def completion_stream(
    transport: Transport, params: CompletionStreamRequest
) -> AsyncIterator[CompletionStreamResponse]:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    async for chunk in transport.call_stream(payload):
        yield CompletionStreamResponse.model_validate(chunk)


async def delete_cache(
    transport: Transport, params: DeleteCacheRequest
) -> DeleteCacheResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return DeleteCacheResponse.model_validate(await transport.call(payload))


async def diffusion_stream(
    transport: Transport, params: DiffusionStreamRequest
) -> AsyncIterator[DiffusionStreamResponse]:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    async for chunk in transport.call_stream(payload):
        yield DiffusionStreamResponse.model_validate(chunk)


async def download_asset(
    transport: Transport, params: DownloadAssetRequest
) -> DownloadAssetResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return DownloadAssetResponse.model_validate(await transport.call(payload))


async def download_asset_with_progress(
    transport: Transport, params: DownloadAssetRequest
) -> AsyncIterator[ModelProgressResponse | DownloadAssetResponse]:
    # Progress events and the terminal reply both arrive through the
    # same stream, distinguished only by each payload's own `type` —
    # call_stream already falls back cleanly to a single terminal
    # chunk if the server ends up replying unary instead (e.g. an
    # operation that doesn't support progress for this method).
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    payload["withProgress"] = True
    async for chunk in transport.call_stream(payload):
        if chunk.get("type") == "modelProgress":
            yield ModelProgressResponse.model_validate(chunk)
        else:
            yield DownloadAssetResponse.model_validate(chunk)


async def embed(transport: Transport, params: EmbedRequest) -> EmbedResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return EmbedResponse.model_validate(await transport.call(payload))


async def finetune(transport: Transport, params: FinetuneRequest) -> FinetuneResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return FinetuneResponse.model_validate(await transport.call(payload))


async def finetune_with_progress(
    transport: Transport, params: FinetuneRequest
) -> AsyncIterator[FinetuneProgressResponse | FinetuneResponse]:
    # Progress events and the terminal reply both arrive through the
    # same stream, distinguished only by each payload's own `type` —
    # call_stream already falls back cleanly to a single terminal
    # chunk if the server ends up replying unary instead (e.g. an
    # operation that doesn't support progress for this method).
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    payload["withProgress"] = True
    async for chunk in transport.call_stream(payload):
        if chunk.get("type") == "finetune:progress":
            yield FinetuneProgressResponse.model_validate(chunk)
        else:
            yield FinetuneResponse.model_validate(chunk)


async def get_loaded_model_info(
    transport: Transport, params: GetLoadedModelInfoRequest
) -> GetLoadedModelInfoResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return GetLoadedModelInfoResponse.model_validate(await transport.call(payload))


async def get_model_info(
    transport: Transport, params: GetModelInfoRequest
) -> GetModelInfoResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return GetModelInfoResponse.model_validate(await transport.call(payload))


async def get_system_resources(
    transport: Transport, params: GetSystemResourcesRequest
) -> GetSystemResourcesResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return GetSystemResourcesResponse.model_validate(await transport.call(payload))


async def heartbeat(
    transport: Transport, params: HeartbeatRequest
) -> HeartbeatResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return HeartbeatResponse.model_validate(await transport.call(payload))


async def load_model(
    transport: Transport, params: LoadModelRequest
) -> LoadModelResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return LoadModelResponse.model_validate(await transport.call(payload))


async def load_model_with_progress(
    transport: Transport, params: LoadModelRequest
) -> AsyncIterator[ModelProgressResponse | LoadModelResponse]:
    # Progress events and the terminal reply both arrive through the
    # same stream, distinguished only by each payload's own `type` —
    # call_stream already falls back cleanly to a single terminal
    # chunk if the server ends up replying unary instead (e.g. an
    # operation that doesn't support progress for this method).
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    payload["withProgress"] = True
    async for chunk in transport.call_stream(payload):
        if chunk.get("type") == "modelProgress":
            yield ModelProgressResponse.model_validate(chunk)
        else:
            yield LoadModelResponse.model_validate(chunk)


async def logging_stream(
    transport: Transport, params: LoggingStreamRequest
) -> AsyncIterator[LoggingStreamResponse]:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    async for chunk in transport.call_stream(payload):
        yield LoggingStreamResponse.model_validate(chunk)


async def model_registry_get_model(
    transport: Transport, params: ModelRegistryGetModelRequest
) -> ModelRegistryGetModelResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return ModelRegistryGetModelResponse.model_validate(await transport.call(payload))


async def model_registry_list(
    transport: Transport, params: ModelRegistryListRequest
) -> ModelRegistryListResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return ModelRegistryListResponse.model_validate(await transport.call(payload))


async def model_registry_search(
    transport: Transport, params: ModelRegistrySearchRequest
) -> ModelRegistrySearchResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return ModelRegistrySearchResponse.model_validate(await transport.call(payload))


async def ocr_stream(
    transport: Transport, params: OcrStreamRequest
) -> AsyncIterator[OcrStreamResponse]:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    async for chunk in transport.call_stream(payload):
        yield OcrStreamResponse.model_validate(chunk)


async def plugin_invoke(
    transport: Transport, params: PluginInvokeRequest
) -> PluginInvokeResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return PluginInvokeResponse.model_validate(await transport.call(payload))


async def plugin_invoke_stream(
    transport: Transport, params: PluginInvokeStreamRequest
) -> AsyncIterator[PluginInvokeStreamResponse]:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    async for chunk in transport.call_stream(payload):
        yield PluginInvokeStreamResponse.model_validate(chunk)


async def provide(transport: Transport, params: ProvideRequest) -> ProvideResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return ProvideResponse.model_validate(await transport.call(payload))


async def rag(transport: Transport, params: RagRequest) -> RagResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return RagResponse.model_validate(await transport.call(payload))


async def rag_with_progress(
    transport: Transport, params: RagRequest
) -> AsyncIterator[RagProgressResponse | RagResponse]:
    # Progress events and the terminal reply both arrive through the
    # same stream, distinguished only by each payload's own `type` —
    # call_stream already falls back cleanly to a single terminal
    # chunk if the server ends up replying unary instead (e.g. an
    # operation that doesn't support progress for this method).
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    payload["withProgress"] = True
    async for chunk in transport.call_stream(payload):
        if chunk.get("type") == "rag:progress":
            yield RagProgressResponse.model_validate(chunk)
        else:
            yield RagResponse.model_validate(chunk)


async def resume(transport: Transport, params: ResumeRequest) -> ResumeResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return ResumeResponse.model_validate(await transport.call(payload))


async def state(transport: Transport, params: StateRequest) -> StateResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return StateResponse.model_validate(await transport.call(payload))


async def stop_provide(
    transport: Transport, params: StopProvideRequest
) -> StopProvideResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return StopProvideResponse.model_validate(await transport.call(payload))


async def suspend(transport: Transport, params: SuspendRequest) -> SuspendResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return SuspendResponse.model_validate(await transport.call(payload))


async def text_to_speech(
    transport: Transport, params: TextToSpeechRequest
) -> AsyncIterator[TextToSpeechResponse]:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    async for chunk in transport.call_stream(payload):
        yield TextToSpeechResponse.model_validate(chunk)


async def text_to_speech_stream(
    transport: Transport, params: TextToSpeechStreamRequest, up: AsyncIterable[bytes]
) -> AsyncIterator[TextToSpeechStreamResponse]:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    async for chunk in transport.call_duplex(payload, up):
        yield TextToSpeechStreamResponse.model_validate(chunk)


async def transcribe(
    transport: Transport, params: TranscribeRequest
) -> AsyncIterator[TranscribeResponse]:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    async for chunk in transport.call_stream(payload):
        yield TranscribeResponse.model_validate(chunk)


async def transcribe_stream(
    transport: Transport, params: TranscribeStreamRequest, up: AsyncIterable[bytes]
) -> AsyncIterator[TranscribeStreamResponse]:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    async for chunk in transport.call_duplex(payload, up):
        yield TranscribeStreamResponse.model_validate(chunk)


async def translate(
    transport: Transport, params: TranslateRequest
) -> AsyncIterator[TranslateResponse]:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    async for chunk in transport.call_stream(payload):
        yield TranslateResponse.model_validate(chunk)


async def unload_model(
    transport: Transport, params: UnloadModelRequest
) -> UnloadModelResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return UnloadModelResponse.model_validate(await transport.call(payload))


async def upscale_stream(
    transport: Transport, params: UpscaleStreamRequest
) -> AsyncIterator[UpscaleStreamResponse]:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    async for chunk in transport.call_stream(payload):
        yield UpscaleStreamResponse.model_validate(chunk)


async def video_stream(
    transport: Transport, params: VideoStreamRequest
) -> AsyncIterator[VideoStreamResponse]:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    async for chunk in transport.call_stream(payload):
        yield VideoStreamResponse.model_validate(chunk)


__all__ = [
    "audio_gen_stream",
    "batch_completion_stream",
    "bci_transcribe",
    "bci_transcribe_stream",
    "cancel",
    "classify",
    "completion_orchestrate",
    "completion_stream",
    "delete_cache",
    "diffusion_stream",
    "download_asset",
    "download_asset_with_progress",
    "embed",
    "finetune",
    "finetune_with_progress",
    "get_loaded_model_info",
    "get_model_info",
    "get_system_resources",
    "heartbeat",
    "load_model",
    "load_model_with_progress",
    "logging_stream",
    "model_registry_get_model",
    "model_registry_list",
    "model_registry_search",
    "ocr_stream",
    "plugin_invoke",
    "plugin_invoke_stream",
    "provide",
    "rag",
    "rag_with_progress",
    "resume",
    "state",
    "stop_provide",
    "suspend",
    "text_to_speech",
    "text_to_speech_stream",
    "transcribe",
    "transcribe_stream",
    "translate",
    "unload_model",
    "upscale_stream",
    "video_stream",
]
