# Generated by scripts/generate.py. Do not edit by hand.
"""Model-type resolution maps mirroring @qvac/sdk's
schemas/model-types.ts (ModelTypeAliases) and schemas/engine-addon-map.ts
(ENGINE_TO_ADDON, LEGACY_ENGINE_TO_CANONICAL), exported via
contract/model-type-maps.json.
"""

from __future__ import annotations

ALIAS_TO_CANONICAL: dict[str, str] = {
    "audiogen": "audiogen-ggml",
    "bci": "bci-whispercpp-transcription",
    "classification": "ggml-classification",
    "diffusion": "sdcpp-generation",
    "embeddings": "llamacpp-embedding",
    "llm": "llamacpp-completion",
    "nmt": "nmtcpp-translation",
    "ocr": "ggml-ocr",
    "parakeet": "parakeet-transcription",
    "tts": "tts-ggml",
    "vla": "ggml-vla",
    "whisper": "whispercpp-transcription",
}

ENGINE_TO_ADDON: dict[str, str] = {
    "audiogen-ggml": "audiogen",
    "bci-whispercpp-transcription": "bci",
    "ggml-classification": "classification",
    "ggml-ocr": "ocr",
    "ggml-vla": "vla",
    "llamacpp-completion": "llm",
    "llamacpp-embedding": "embeddings",
    "nmtcpp-translation": "nmt",
    "onnx-tts": "tts",
    "onnx-vad": "vad",
    "parakeet-transcription": "parakeet",
    "sdcpp-generation": "diffusion",
    "tts-ggml": "tts",
    "whispercpp-transcription": "whisper",
}

LEGACY_ENGINE_TO_CANONICAL: dict[str, str] = {
    "@qvac/audiogen": "audiogen-ggml",
    "@qvac/audiogen-ggml": "audiogen-ggml",
    "@qvac/bci-whispercpp": "bci-whispercpp-transcription",
    "@qvac/classification-ggml": "ggml-classification",
    "@qvac/diffusion-cpp": "sdcpp-generation",
    "@qvac/embed-llamacpp": "llamacpp-embedding",
    "@qvac/llm-llamacpp": "llamacpp-completion",
    "@qvac/ocr-ggml": "ggml-ocr",
    "@qvac/ocr-onnx": "ggml-ocr",
    "@qvac/transcription-parakeet": "parakeet-transcription",
    "@qvac/transcription-whispercpp": "whispercpp-transcription",
    "@qvac/translation-llamacpp": "nmtcpp-translation",
    "@qvac/translation-nmtcpp": "nmtcpp-translation",
    "@qvac/tts": "tts-ggml",
    "@qvac/tts-ggml": "tts-ggml",
    "@qvac/tts-onnx": "tts-ggml",
    "@qvac/vad-silero": "onnx-vad",
    "@qvac/vla-ggml": "ggml-vla",
    "audiogen": "audiogen-ggml",
    "bci": "bci-whispercpp-transcription",
    "classification": "ggml-classification",
    "diffusion": "sdcpp-generation",
    "embedding": "llamacpp-embedding",
    "generation": "llamacpp-completion",
    "ocr": "ggml-ocr",
    "onnx-ocr": "ggml-ocr",
    "transcription": "whispercpp-transcription",
    "translation": "nmtcpp-translation",
    "tts": "tts-ggml",
    "vad": "onnx-vad",
    "vla": "ggml-vla",
}

__all__ = [
    "ALIAS_TO_CANONICAL",
    "ENGINE_TO_ADDON",
    "LEGACY_ENGINE_TO_CANONICAL",
]
