import { z } from 'zod'
import {
  transcribeSegmentSchema,
  transcribeStatsSchema,
  type TranscribeSegment
} from '@/schemas/transcription'

// Neural-signal binary input. The BCI addon consumes a raw neural buffer
// (not audio): pass it inline as base64 or point at a local `.bin` file.
export const neuralInputSchema = z.discriminatedUnion('type', [
  z.object({
    type: z.literal('base64').describe('Inline base64-encoded neural bytes.'),
    value: z.string().describe('Base64-encoded contents of a BCI neural `.bin` recording.')
  }),
  z.object({
    type: z.literal('filePath').describe('Local neural `.bin` file path.'),
    value: z.string().describe('Path to a BCI neural `.bin` recording on the provider.')
  })
])

const bciTranscribeBaseSchema = z.object({
  modelId: z.string().describe('Identifier returned by `loadModel()` for a loaded BCI model.'),
  metadata: z
    .boolean()
    .optional()
    .describe(
      'When true, responses yield transcript segment metadata objects (`{ text, startMs, endMs, append, id }`) instead of joined text.'
    )
})

export const bciTranscribeParamsSchema = bciTranscribeBaseSchema.extend({
  neuralData: neuralInputSchema.describe(
    'Fixed wire shape for BCI neural input: either inline base64 neural bytes or a provider-local `.bin` file path.'
  )
})

export const bciTranscribeClientParamsSchema = bciTranscribeBaseSchema.extend({
  neuralData: z
    .union([z.string(), z.instanceof(Uint8Array)])
    .describe(
      'Convenience client input for BCI neural data: pass a local/provider `.bin` file path as a string, or raw neural bytes as a `Uint8Array`. The client converts this to `neuralInputSchema` before sending the request.'
    )
})

export const bciTranscribeRequestSchema = bciTranscribeParamsSchema.extend({
  type: z.literal('bciTranscribe'),
  requestId: z
    .string()
    .min(1)
    .optional()
    .describe(
      'Stable identifier for this in-flight BCI transcription, generated by the caller at call time. Surfaces on the registry so callers can target it with `cancel({ requestId })`. Optional — falls back to a generated id when the field is missing.'
    )
})

const bciTranscriptionResultBase = z.object({
  text: z.string().optional(),
  done: z.boolean().optional(),
  stats: transcribeStatsSchema.optional(),
  error: z.string().optional(),
  segment: transcribeSegmentSchema.optional()
})

export const bciTranscribeResponseSchema = bciTranscriptionResultBase.extend({
  type: z.literal('bciTranscribe')
})

/**
 * Per-call overrides for the BCI addon's sliding-window streaming
 * (`transcribeStream`). Each field maps 1:1 to the addon's `streamOpts`;
 * any field omitted falls back to the addon default.
 */
export const bciStreamOptsSchema = z
  .object({
    windowTimesteps: z
      .number()
      .int()
      .positive()
      .optional()
      .describe('Decode window size in timesteps (addon default: 1500).'),
    hopTimesteps: z
      .number()
      .int()
      .positive()
      .optional()
      .describe(
        'How far the window advances between decodes (addon default: 500). Must be < windowTimesteps.'
      ),
    emit: z
      .enum(['delta', 'full'])
      .optional()
      .describe(
        "'delta' (default) emits only the newly-discovered tail per window; 'full' emits the full running transcript each update."
      )
  })
  .refine(
    (opts) =>
      opts.windowTimesteps === undefined ||
      opts.hopTimesteps === undefined ||
      opts.hopTimesteps < opts.windowTimesteps,
    {
      message: 'hopTimesteps must be < windowTimesteps',
      path: ['hopTimesteps']
    }
  )

export const bciTranscribeStreamRequestSchema = bciTranscribeBaseSchema.extend({
  type: z.literal('bciTranscribeStream'),
  streamOpts: bciStreamOptsSchema.optional(),
  requestId: z
    .string()
    .min(1)
    .optional()
    .describe(
      'Stable identifier for this in-flight duplex BCI transcription, generated by the caller at call time. Surfaces on the registry so callers can target it with `cancel({ requestId })`. Optional — falls back to a generated id when the field is missing.'
    )
})

export const bciTranscribeStreamResponseSchema = bciTranscriptionResultBase.extend({
  type: z.literal('bciTranscribeStream')
})

export type NeuralInput = z.infer<typeof neuralInputSchema>
export type BciTranscribeParams = z.infer<typeof bciTranscribeParamsSchema>
export type BciTranscribeRequest = z.infer<typeof bciTranscribeRequestSchema>
export type BciTranscribeResponse = z.infer<typeof bciTranscribeResponseSchema>
export type BciTranscribeClientParamsParsed = z.output<typeof bciTranscribeClientParamsSchema>
export type BciStreamOpts = z.infer<typeof bciStreamOptsSchema>
export type BciTranscribeStreamRequest = z.infer<typeof bciTranscribeStreamRequestSchema>
export type BciTranscribeStreamResponse = z.infer<typeof bciTranscribeStreamResponseSchema>

/** Client parameters for `bciTranscribe()`. */
export interface BciTranscribeClientParams {
  /** Identifier returned by `loadModel()` for a loaded BCI model. */
  modelId: string
  /**
   * BCI neural input. A string is treated as a local/provider `.bin` file path;
   * a `Uint8Array` is treated as raw neural bytes and sent as base64 on the
   * wire.
   */
  neuralData: string | Uint8Array
  /**
   * When true, resolves to transcript segment metadata objects
   * (`{ text, startMs, endMs, append, id }`) instead of joined text.
   */
  metadata?: boolean
}

export type BciTranscribeStreamClientParams = {
  modelId: string
  metadata?: boolean
  windowTimesteps?: number
  hopTimesteps?: number
  emit?: 'delta' | 'full'
}

export interface BciTranscribeStreamSession {
  /**
   * Stable id for this in-flight BCI stream. Pass to `cancel({ requestId })`
   * to target this duplex session without cancelling other work on the model.
   */
  requestId: string
  write(neuralChunk: Uint8Array): void
  end(): void
  destroy(): void
  [Symbol.asyncIterator](): AsyncIterator<string>
}

export interface BciTranscribeStreamMetadataSession {
  /**
   * Stable id for this in-flight BCI stream. Pass to `cancel({ requestId })`
   * to target this duplex session without cancelling other work on the model.
   */
  requestId: string
  write(neuralChunk: Uint8Array): void
  end(): void
  destroy(): void
  [Symbol.asyncIterator](): AsyncIterator<TranscribeSegment>
}
