import { z } from 'zod'
import {
  toolCallSchema,
  toolCallErrorSchema,
  type Tool,
  type ToolCallWithCall
} from '@/schemas/tools'
import type { ToolDialect } from '@/schemas/completion-stream'

export const completionStatsSchema = z.object({
  timeToFirstToken: z.number().optional(),
  tokensPerSecond: z.number().optional(),
  cacheTokens: z.number().optional(),
  promptTokens: z.number().optional(),
  // Decode count (`llama_perf` `n_eval`) — length / KV-cache budget decisions.
  generatedTokens: z.number().optional(),
  // Non-empty addon stream pieces — prefer for usage reporting when present.
  emittedTokens: z.number().optional(),
  avgConcurrentSeq: z.number().optional(),
  backendDevice: z.enum(['cpu', 'gpu']).optional()
})

export type CompletionStats = z.infer<typeof completionStatsSchema>

export const seqSchema = z.number().int().nonnegative()

export const contentDeltaEventSchema = z.object({
  type: z.literal('contentDelta'),
  seq: seqSchema,
  text: z.string()
})

export const rawDeltaEventSchema = z.object({
  type: z.literal('rawDelta'),
  seq: seqSchema,
  text: z.string()
})

export const thinkingDeltaEventSchema = z.object({
  type: z.literal('thinkingDelta'),
  seq: seqSchema,
  text: z.string()
})

export const toolCallEventSchema = z.object({
  type: z.literal('toolCall'),
  seq: seqSchema,
  call: toolCallSchema
})

export const toolErrorEventSchema = z.object({
  type: z.literal('toolError'),
  seq: seqSchema,
  error: toolCallErrorSchema
})

export const statsEventSchema = z.object({
  type: z.literal('completionStats'),
  seq: seqSchema,
  stats: completionStatsSchema
})

export const completionErrorSchema = z.object({
  message: z.string()
})

const rawOutputSchema = z.object({
  fullText: z.string()
})

// `"cancelled"` is a clean termination, not a mid-stream failure: the
// stream ended on purpose because the request was aborted, just not at
// EOS. It rides the success-done path (alongside "eos" / "length" /
// "stopSequence") so consumers iterating `events` see the stream end
// naturally. The companion error path (`errorDoneSchema` below) keeps
// `stopReason: "error"` for actual mid-stream failures where the
// partial state is unsafe to use. The promise-aggregates on the
// `CompletionRun` (`final` / `text` / `toolCalls` / `stats`)
// reject with `InferenceCancelledError` carrying the partial state — see
// `api/completion-stream.ts` for the rejection plumbing.
const stopReasonEnum = z.enum(['eos', 'length', 'stopSequence', 'cancelled'])

const successDoneSchema = z
  .object({
    type: z.literal('completionDone'),
    seq: seqSchema,
    stopReason: stopReasonEnum.optional(),
    raw: rawOutputSchema.optional()
  })
  .strict()

const errorDoneSchema = z
  .object({
    type: z.literal('completionDone'),
    seq: seqSchema,
    stopReason: z.literal('error'),
    error: completionErrorSchema,
    raw: rawOutputSchema.optional()
  })
  .strict()

export const doneEventSchema = z.union([errorDoneSchema, successDoneSchema])

export const completionEventSchema = z.union([
  contentDeltaEventSchema,
  rawDeltaEventSchema,
  thinkingDeltaEventSchema,
  toolCallEventSchema,
  toolErrorEventSchema,
  statsEventSchema,
  errorDoneSchema,
  successDoneSchema
])

export type ContentDeltaEvent = z.infer<typeof contentDeltaEventSchema>
export type RawDeltaEvent = z.infer<typeof rawDeltaEventSchema>
export type ThinkingDeltaEvent = z.infer<typeof thinkingDeltaEventSchema>
export type ToolCallEvent = z.infer<typeof toolCallEventSchema>
export type ToolErrorEvent = z.infer<typeof toolErrorEventSchema>
export type StatsEvent = z.infer<typeof statsEventSchema>
export type CompletionError = z.infer<typeof completionErrorSchema>
export type DoneEvent = z.infer<typeof doneEventSchema>
export type CompletionEvent = z.infer<typeof completionEventSchema>
export type StopReason = z.infer<typeof stopReasonEnum>

export type CompletionFinal = {
  contentText: string
  thinkingText?: string
  toolCalls: ToolCallWithCall[]
  stats?: CompletionStats
  stopReason?: StopReason
  raw: {
    fullText: string
  }
  /**
   * Canonical assistant text to push back into `history` for the next turn
   * when using `kvCache: true` (auto-cache). Equals the assistant content
   * we persisted to the cache key on this turn, so re-using it
   * verbatim guarantees a cache hit on the next call.
   *
   * Derived from `raw.fullText` (or `contentText` if the addon didn't
   * emit raw text) by stripping `<think>` reasoning blocks and trimming
   * surrounding whitespace — see `normalizeAssistantCacheContent`.
   *
   * Tool-call turns currently can't be auto-cached, so this
   * field is omitted when `toolCalls.length > 0`.
   */
  cacheableAssistantContent?: string
}

export type CompletionRun = {
  /**
   * Stable identifier for this run, generated by the caller at call time
   * (UUIDv4 when `crypto.randomUUID` is available, otherwise an opaque
   * random hex token) and available synchronously the moment
   * `completion(...)` returns. Pass it to `cancel({ requestId })` to
   * target this specific request without affecting any other inference
   * running on the same model. The cancel only takes effect once the
   * request has begun, so a cancel issued in the same tick
   * as `completion(...)` may race the begin and is logged as a no-match.
   */
  requestId: string
  /** Ordered stream of typed completion events — the canonical consumption API. */
  events: AsyncIterable<CompletionEvent>
  /** Resolves when the stream ends with aggregated content, thinking, tool calls, stats, and raw output. */
  final: Promise<CompletionFinal>

  tokenStream: AsyncGenerator<string>
  toolCallStream: AsyncGenerator<ToolCallEvent>
  text: Promise<string>
  toolCalls: Promise<ToolCallWithCall[]>
  stats: Promise<CompletionStats | undefined>
}

export type ToolCallingCapability = 'textParse' | 'none'
export type ThinkingFramingCapability = 'thinkTags' | 'none'

export type PluginCapabilities = {
  toolCalling: ToolCallingCapability
  thinkingFraming: ThinkingFramingCapability
}

export const DEFAULT_PLUGIN_CAPABILITIES: PluginCapabilities = {
  toolCalling: 'none',
  thinkingFraming: 'none'
}

export type NormalizerConfig = {
  capabilities: PluginCapabilities
  tools: Tool[]
  captureThinking: boolean
  emitRawDeltas: boolean
  // Defaults to "hermes" (`<tool_call>...` framing + JSON-payload fallbacks)
  // when omitted. "json" is the no-framing pure JSON-payload dialect.
  toolDialect?: ToolDialect
}
