import { z } from 'zod'
import type { AbortController } from 'bare-abort-controller'
import type { ModelProgressUpdate } from '@/schemas/load-model'
import { modelSrcInputSchema, modelInputToSrcSchema } from '@/schemas/model-src-utils'

const downloadAssetOptionsBaseSchema = z.object({
  assetSrc: modelSrcInputSchema,
  seed: z.boolean().optional()
})

export const downloadAssetOptionsSchema = downloadAssetOptionsBaseSchema.transform((data) => ({
  ...data,
  seed: data.seed ?? false
}))

export const downloadAssetOptionsToRequestSchema = downloadAssetOptionsBaseSchema
  .extend({
    onProgress: z.unknown().optional(),
    withProgress: z.boolean().optional(),
    requestId: z.string().min(1).optional()
  })
  .transform((data) => {
    const out: {
      type: 'downloadAsset'
      assetSrc: string
      withProgress: boolean
      seed: boolean
      requestId?: string
    } = {
      type: 'downloadAsset' as const,
      assetSrc: modelInputToSrcSchema.parse(data.assetSrc),
      withProgress: data.withProgress ?? !!data.onProgress,
      seed: data.seed ?? false
    }
    if (data.requestId !== undefined) out.requestId = data.requestId
    return out
  })

export const downloadAssetRequestSchema = z
  .object({
    type: z.literal('downloadAsset'),
    assetSrc: z.string(),
    withProgress: z.boolean().optional(),
    seed: z.boolean().optional(),
    requestId: z
      .string()
      .min(1)
      .optional()
      .describe(
        'Stable identifier for this in-flight download, generated by the caller at call time. Optional — falls back to a generated id when the field is missing. Exposed on the decorated promise so callers can target this download with `cancel({ requestId })`.'
      )
  })
  .transform((data) => ({
    ...data,
    seed: data.seed ?? false
  }))

export const downloadAssetResponseSchema = z.object({
  type: z.literal('downloadAsset'),
  success: z.boolean(),
  assetId: z.string().optional(),
  error: z.string().optional()
})

const downloadTypes = ['hyperdrive', 'http', 'registry'] as const
export const downloadTypeSchema = z.enum(downloadTypes)
export const sourceTypeSchema = z.enum([...downloadTypes, 'filesystem'])

export const downloadMetadataSchema = z.object({
  key: z.string(),
  startTime: z.number(),
  type: downloadTypeSchema
})

export const hyperdriveDownloadMetadataSchema = downloadMetadataSchema.extend({
  type: z.literal('hyperdrive'),
  hyperdriveKey: z.string(),
  modelFileName: z.string()
})

export const httpDownloadMetadataSchema = downloadMetadataSchema.extend({
  type: z.literal('http'),
  url: z.url(),
  modelPath: z.string()
})

export const registryDownloadMetadataSchema = downloadMetadataSchema.extend({
  type: z.literal('registry'),
  registryPath: z.string()
})

export type DownloadAssetOptions = z.input<typeof downloadAssetOptionsSchema> & {
  onProgress?: (progress: ModelProgressUpdate) => void
}
export type DownloadAssetRequest = z.infer<typeof downloadAssetRequestSchema>
export type DownloadAssetResponse = z.infer<typeof downloadAssetResponseSchema>
export type DownloadType = z.infer<typeof downloadTypeSchema>
export type SourceType = z.infer<typeof sourceTypeSchema>
export type BaseDownloadEntry = z.infer<typeof downloadMetadataSchema> & {
  promise: Promise<string>
  abortController: AbortController
  onProgress?: (progress: ModelProgressUpdate) => void
}
export type HyperdriveDownloadEntry = BaseDownloadEntry &
  z.infer<typeof hyperdriveDownloadMetadataSchema>
export type HttpDownloadEntry = BaseDownloadEntry & z.infer<typeof httpDownloadMetadataSchema>
export type RegistryDownloadEntry = BaseDownloadEntry &
  z.infer<typeof registryDownloadMetadataSchema>
export type DownloadEntry = HyperdriveDownloadEntry | HttpDownloadEntry | RegistryDownloadEntry
