import { z } from 'zod'
import type Buffer from 'bare-buffer'

export const audioInputSchema = z.discriminatedUnion('type', [
  z.object({
    type: z.literal('base64'),
    value: z.string()
  }),
  z.object({
    type: z.literal('filePath'),
    value: z.string()
  })
])

const transcribeBaseSchema = z.object({
  modelId: z.string(),
  /**
   * Initial transcription prompt. Whisper engine only — silently
   * ignored by the parakeet engine, which has no equivalent prompting
   * surface in `qvac-parakeet.cpp`.
   */
  prompt: z.string().optional(),
  metadata: z.boolean().optional()
})

export const transcribeParamsSchema = transcribeBaseSchema.extend({
  audioChunk: audioInputSchema
})

export const transcribeStatsSchema = z.object({
  audioDuration: z.number().optional(),
  realTimeFactor: z.number().optional(),
  tokensPerSecond: z.number().optional(),
  totalTokens: z.number().optional(),
  totalSegments: z.number().optional(),
  whisperEncodeTime: z.number().optional(),
  whisperDecodeTime: z.number().optional(),
  encoderTime: z.number().optional(),
  decoderTime: z.number().optional(),
  melSpecTime: z.number().optional(),
  // Backend selection captured once at model load.
  // `0` CPU / `1` GPU; `backendId` codes the GPU family (see the addon's
  // BackendId enum). gpu memory fields are `-1` when the backend exposes
  // no accounting, and absent entirely for the parakeet engine.
  backendDevice: z.number().optional(),
  backendId: z.number().optional(),
  gpuUnsupported: z.number().optional(),
  gpuMemTotalMb: z.number().optional(),
  gpuMemFreeMb: z.number().optional()
})

export const transcribeSegmentSchema = z.object({
  text: z.string(),
  startMs: z.number(),
  endMs: z.number(),
  append: z.boolean(),
  id: z.number()
})

export const vadStateEventSchema = z.object({
  speaking: z.boolean(),
  probability: z.number()
})

export const whisperEndOfTurnEventSchema = z.object({
  source: z.literal('whisper'),
  silenceDurationMs: z.number()
})

export const parakeetEndOfTurnEventSchema = z.object({
  source: z.literal('parakeet')
})

const endOfTurnDiscriminatedSchema = z.discriminatedUnion('source', [
  whisperEndOfTurnEventSchema,
  parakeetEndOfTurnEventSchema
])

/** Legacy whisper wire frames omitted `source` and only sent `silenceDurationMs`. */
function normalizeEndOfTurnWire(value: unknown) {
  if (
    typeof value === 'object' &&
    value !== null &&
    !('source' in value) &&
    typeof (value as { silenceDurationMs?: unknown }).silenceDurationMs === 'number'
  ) {
    return {
      source: 'whisper' as const,
      silenceDurationMs: (value as { silenceDurationMs: number }).silenceDurationMs
    }
  }
  return value
}

export const endOfTurnEventSchema = z.preprocess(
  normalizeEndOfTurnWire,
  endOfTurnDiscriminatedSchema
)

export const transcribeRequestSchema = transcribeParamsSchema.extend({
  type: z.literal('transcribe'),
  requestId: z
    .string()
    .min(1)
    .optional()
    .describe(
      'Stable identifier for this in-flight transcription, generated by the caller at call time. Surfaces on the registry so callers can target it with `cancel({ requestId })`. Optional — falls back to a generated id when the field is missing.'
    )
})

const transcriptionResultBase = z.object({
  text: z.string().optional(),
  done: z.boolean().optional(),
  stats: transcribeStatsSchema.optional(),
  error: z.string().optional(),
  segment: transcribeSegmentSchema.optional(),
  vad: vadStateEventSchema.optional(),
  endOfTurn: endOfTurnEventSchema.optional()
})

export const transcribeResponseSchema = transcriptionResultBase.extend({
  type: z.literal('transcribe')
})

export type AudioInput = z.infer<typeof audioInputSchema>
export type TranscribeParams = z.infer<typeof transcribeParamsSchema>
export type TranscribeSegment = z.infer<typeof transcribeSegmentSchema>
export type TranscribeClientParams = {
  modelId: string
  audioChunk: string | Buffer
  prompt?: string
  metadata?: boolean
}
export type TranscribeRequest = z.infer<typeof transcribeRequestSchema>
export type TranscribeResponse = z.infer<typeof transcribeResponseSchema>

/**
 * Per-call overrides for parakeet's duplex streaming session.
 *
 * Each field maps to its `streaming*`-prefixed counterpart in
 * `parakeetConfig` (see `parakeetRuntimeConfigSchema`). The `streaming`
 * prefix is intentionally dropped here because every field on this
 * object is already namespaced under the `parakeetStreamingConfig`
 * field of `transcribeStream({ ... })`. Any field omitted falls back
 * to the load-time value.
 */
export const parakeetStreamingRunConfigSchema = z.object({
  chunkMs: z.number().int().positive().optional(),
  historyMs: z.number().int().positive().optional(),
  leftContextMs: z.number().int().nonnegative().optional(),
  rightLookaheadMs: z.number().int().nonnegative().optional(),
  emitPartials: z.boolean().optional(),
  emitEnergyVad: z.boolean().optional(),
  spkCacheEnable: z.boolean().optional(),
  spkCacheLen: z.number().int().positive().optional(),
  fifoLen: z.number().int().positive().optional(),
  chunkLeftContextMs: z.number().int().nonnegative().optional(),
  chunkRightContextMs: z.number().int().nonnegative().optional(),
  spkCacheUpdatePeriod: z.number().int().positive().optional()
})

export type ParakeetStreamingRunConfig = z.infer<typeof parakeetStreamingRunConfigSchema>

export const transcribeStreamRequestSchema = transcribeBaseSchema.extend({
  type: z.literal('transcribeStream'),
  emitVadEvents: z.boolean().optional(),
  endOfTurnSilenceMs: z
    .number()
    .int()
    .nonnegative()
    .optional()
    .describe(
      'Silence (ms) before an endOfTurn event fires. 0 or unset disables end-of-turn detection entirely. Whisper engine only.'
    ),
  vadRunIntervalMs: z.number().int().positive().optional(),
  parakeetStreamingConfig: parakeetStreamingRunConfigSchema.optional(),
  requestId: z
    .string()
    .min(1)
    .optional()
    .describe(
      'Stable identifier for this in-flight duplex transcription, generated by the caller at call time. Surfaces on the registry so callers can target it with `cancel({ requestId })`. Optional — falls back to a generated id when the field is missing.'
    )
})

export const transcribeStreamResponseSchema = transcriptionResultBase.extend({
  type: z.literal('transcribeStream')
})

export type TranscribeStreamRequest = z.infer<typeof transcribeStreamRequestSchema>
export type TranscribeStreamResponse = z.infer<typeof transcribeStreamResponseSchema>

export type TranscribeStreamClientParams = {
  modelId: string
  prompt?: string
  metadata?: boolean
  emitVadEvents?: boolean
  endOfTurnSilenceMs?: number
  vadRunIntervalMs?: number
  parakeetStreamingConfig?: ParakeetStreamingRunConfig
}

export interface TranscribeStreamSession {
  write(audioChunk: Uint8Array): void
  end(): void
  destroy(): void
  [Symbol.asyncIterator](): AsyncIterator<string>
}

export interface TranscribeStreamMetadataSession {
  write(audioChunk: Uint8Array): void
  end(): void
  destroy(): void
  [Symbol.asyncIterator](): AsyncIterator<TranscribeSegment>
}

export type VadStateEvent = z.infer<typeof vadStateEventSchema>
export type WhisperEndOfTurnEvent = z.infer<typeof whisperEndOfTurnEventSchema>
export type ParakeetEndOfTurnEvent = z.infer<typeof parakeetEndOfTurnEventSchema>
export type EndOfTurnEvent = z.infer<typeof endOfTurnEventSchema>

export type TranscribeStreamEvent =
  | { type: 'text'; text: string }
  | { type: 'segment'; segment: TranscribeSegment }
  | ({ type: 'vad' } & VadStateEvent)
  | ({ type: 'endOfTurn' } & EndOfTurnEvent)

export interface TranscribeStreamConversationSession {
  write(audioChunk: Uint8Array): void
  end(): void
  destroy(): void
  [Symbol.asyncIterator](): AsyncIterator<TranscribeStreamEvent>
}

export type TranscribeStats = z.infer<typeof transcribeStatsSchema>
